# Generated by Django 2.1.4 on 2019-01-31 16:17

from django.db import migrations, models
import django.db.models.deletion
import info.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=5000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=info.models.user_directory_path)),
                ('source', models.CharField(max_length=100)),
                ('isfootball', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=info.models.player_pic_path)),
                ('age', models.IntegerField()),
                ('pheight', models.IntegerField()),
                ('pweight', models.IntegerField()),
                ('nationality', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('isfootball', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelateNewsPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.News')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Player')),
            ],
        ),
        migrations.CreateModel(
            name='RelateNewsTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.News')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonBasketball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField(unique=True)),
                ('partab2', models.IntegerField()),
                ('partab3', models.IntegerField()),
                ('fouls', models.IntegerField()),
                ('rebound', models.IntegerField()),
                ('game_time', models.IntegerField()),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.Player')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonFootball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField(unique=True)),
                ('goals', models.IntegerField()),
                ('pas', models.IntegerField()),
                ('fouls', models.IntegerField()),
                ('carts', models.IntegerField()),
                ('game_time', models.IntegerField()),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('news', models.ManyToManyField(to='info.News')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('isfootball', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='relatenewsteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Team'),
        ),
    ]
