# Generated by Django 2.1.4 on 2019-01-31 16:17

from django.db import migrations, models
import django.db.models.deletion
import games.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketbalState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField()),
                ('f_total_score', models.IntegerField()),
                ('s_total_score', models.IntegerField()),
                ('f_2points_shots', models.IntegerField()),
                ('s_2points_shots', models.IntegerField()),
                ('f_3points_shots', models.IntegerField()),
                ('s_3points_shots', models.IntegerField()),
                ('f_fouls', models.IntegerField()),
                ('s_fouls', models.IntegerField()),
                ('f_penalties', models.IntegerField()),
                ('s_penalties', models.IntegerField()),
                ('f_rebounds', models.IntegerField()),
                ('s_rebounds', models.IntegerField()),
                ('f_1st_quarter_score', models.IntegerField()),
                ('s_1st_quarter_score', models.IntegerField()),
                ('f_2nd_quarter_score', models.IntegerField()),
                ('s_2nd_quarter_score', models.IntegerField()),
                ('f_3rd_quarter_score', models.IntegerField()),
                ('s_3rd_quarter_score', models.IntegerField()),
                ('f_4th_quarter_score', models.IntegerField()),
                ('s_4th_quarter_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('ec', 'تعویض'), ('rc', 'کارت قرمز'), ('yc', 'کارت زرد'), ('go', 'گل'), ('rb', 'ریباند'), ('2p', 'دو امتیازی'), ('3p', 'سه امتیازی')], max_length=2)),
                ('time', models.IntegerField()),
                ('event_pic', models.CharField(max_length=30)),
                ('event_color_class', models.CharField(blank=True, choices=[('ec', 'table-info'), ('rc', 'bg-danger'), ('yc', 'table-danger'), ('go', 'bg-success'), ('rb', 'table-danger'), ('2p', 'table-success'), ('3p', 'bg-success')], default='ec', max_length=4, null=True)),
                ('first_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_player', to='info.Player')),
            ],
        ),
        migrations.CreateModel(
            name='FootballState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField()),
                ('f_score', models.IntegerField()),
                ('s_score', models.IntegerField()),
                ('f_corner', models.IntegerField()),
                ('s_corner', models.IntegerField()),
                ('f_chances', models.IntegerField()),
                ('s_chances', models.IntegerField()),
                ('f_possession', models.IntegerField()),
                ('s_possession', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('brief_description', models.CharField(max_length=100)),
                ('stadium', models.CharField(max_length=50)),
                ('is_football', models.BooleanField()),
                ('date', models.DateTimeField()),
                ('week', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=games.models.user_directory_path)),
                ('basketball_states', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.BasketbalState')),
                ('best_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.Player')),
                ('football_states', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.FootballState')),
                ('team1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1_reverse', to='info.Team')),
                ('team2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2_reverse', to='info.Team')),
            ],
        ),
        migrations.CreateModel(
            name='GamePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=games.models.game_pic_directory)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
        ),
        migrations.CreateModel(
            name='GameVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to=games.models.game_video_directory)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=games.models.game_video_directory)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=200)),
                ('is_football', models.BooleanField()),
                ('start_date', models.DateField()),
                ('finished', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LeagueGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.League')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField()),
                ('loses', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('goals_scored', models.IntegerField()),
                ('goals_received', models.IntegerField()),
                ('goals_diff', models.IntegerField()),
                ('score', models.IntegerField()),
                ('game', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.League')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='info.Team')),
            ],
        ),
        migrations.CreateModel(
            name='RelateNewsGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.News')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='games.Game'),
        ),
        migrations.AddField(
            model_name='event',
            name='second_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_player', to='info.Player'),
        ),
        migrations.AddField(
            model_name='event',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='info.Team'),
        ),
    ]
