# Generated by Django 2.1.4 on 2019-01-24 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketbalState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField()),
                ('f_total_score', models.IntegerField()),
                ('s_total_score', models.IntegerField()),
                ('f_2points_shots', models.IntegerField()),
                ('s_2points_shots', models.IntegerField()),
                ('f_3points_shots', models.IntegerField()),
                ('s_3points_shots', models.IntegerField()),
                ('f_fouls', models.IntegerField()),
                ('s_fouls', models.IntegerField()),
                ('f_penalties', models.IntegerField()),
                ('s_penalties', models.IntegerField()),
                ('f_rebounds', models.IntegerField()),
                ('s_rebounds', models.IntegerField()),
                ('f_1st_quarter_score', models.IntegerField()),
                ('s_1st_quarter_score', models.IntegerField()),
                ('f_2nd_quarter_score', models.IntegerField()),
                ('s_2nd_quarter_score', models.IntegerField()),
                ('f_3rd_quarter_score', models.IntegerField()),
                ('s_3rd_quarter_score', models.IntegerField()),
                ('f_4th_quarter_score', models.IntegerField()),
                ('s_4th_quarter_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('ec', 'exchange'), ('rc', 'red card'), ('yc', 'yellow card'), ('go', 'goal'), ('rb', 'rebound'), ('2p', '2 point'), ('3p', '3 point')], max_length=2)),
                ('time', models.TimeField()),
                ('event_pic', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FootballState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField()),
                ('f_score', models.IntegerField()),
                ('s_score', models.IntegerField()),
                ('f_corner', models.IntegerField()),
                ('s_corner', models.IntegerField()),
                ('f_chances', models.IntegerField()),
                ('s_chances', models.IntegerField()),
                ('f_possession', models.IntegerField()),
                ('s_possession', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_football', models.BooleanField()),
                ('basketball_states', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basketball_state', to='games.BasketbalState')),
                ('football_states', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='football_state', to='games.FootballState')),
                ('team1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1_reverse', to='info.Team')),
                ('team2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2_reverse', to='info.Team')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('finished', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LeagueGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_game', to='games.Game')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league', to='games.League')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField()),
                ('loses', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('goals_scored', models.IntegerField()),
                ('goals_received', models.IntegerField()),
                ('goals_diff', models.IntegerField()),
                ('score', models.IntegerField()),
                ('game', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.League')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='info.Team')),
            ],
        ),
        migrations.CreateModel(
            name='RelateNewsGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.News')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
        ),
    ]
