# Generated by Django 2.1.4 on 2019-02-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_color_class',
            field=models.CharField(blank=True, choices=[('table-info', 'تعویض'), ('bg-danger', 'کارت قرمز'), ('table-danger', 'کارت زرد'), ('bg-success', 'گل'), ('table-danger', 'ریباند'), ('table-success', 'دو امتیاز'), ('bg-success', 'سه امتیاز')], default='ec', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(choices=[('تعویض', 'تعویض'), ('کارت قرمز', 'کارت قرمز'), ('کارت زرد', 'کارت زرد'), ('گلgo', 'گل'), ('ریباند', 'ریباند'), ('دو امتیازی', 'دو امتیازی'), ('سه امتیازی', 'سه امتیازی')], max_length=2),
        ),
    ]
