# Generated by Django 2.1.4 on 2019-01-26 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='basketball_states',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.BasketbalState'),
        ),
        migrations.AlterField(
            model_name='game',
            name='football_states',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.FootballState'),
        ),
        migrations.AlterField(
            model_name='leaguegame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
        ),
        migrations.AlterField(
            model_name='leaguegame',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.League'),
        ),
    ]
