# Generated by Django 2.1.4 on 2019-02-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20190201_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(choices=[('تعویض', 'تعویض'), ('کارت قرمز', 'کارت قرمز'), ('کارت زرد', 'کارت زرد'), ('گلgo', 'گل'), ('ریباند', 'ریباند'), ('دو امتیازی', 'دو امتیازی'), ('سه امتیازی', 'سه امتیازی')], max_length=40),
        ),
    ]
