# Generated by Django 2.1.4 on 2019-02-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20190201_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_color_class',
            field=models.CharField(blank=True, choices=[('table-info', 'تعویض'), ('bg-danger', 'کارت قرمز'), ('table-danger', 'کارت زرد'), ('bg-success', 'گل'), ('table-danger', 'ریباند'), ('table-success', 'دو امتیاز'), ('bg-success', 'سه امتیاز')], default='ec', max_length=40, null=True),
        ),
    ]
