# Generated by Django 2.1.4 on 2019-01-26 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20190126_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguegame',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
        ),
    ]
