# Generated by Django 2.1.4 on 2019-01-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='is_football',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
