# Generated by Django 2.1.4 on 2019-02-01 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
        ('games', '0006_playersgame_bench'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketPLayerGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_time', models.IntegerField()),
                ('rebounds', models.IntegerField()),
                ('total_in_game', models.IntegerField()),
                ('point_3', models.IntegerField()),
                ('point_2', models.IntegerField()),
                ('bench', models.BooleanField(default=False)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Game')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.Player')),
            ],
        ),
    ]
