# Generated by Django 2.1.4 on 2019-02-01 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_basketplayergame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketplayergame',
            name='bench',
        ),
    ]
